kind: pipeline
name: default

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.cache

  - name: build_binary
    image: golang
    environment:
    privileged: true
    commands:
      - export GOTMPDIR=.cache
      - go test
      - go build
      - mv lico_alone ./docker/
      - ls $GOPATH/pkg/mod
      - ls -al

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.cache

  - name: build_docker_image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_hub_user_name
      password:
        from_secret: docker_hub_password
      dockerfile: ./docker/Dockerfile
      context: ./docker/
      repo: lico603/lico_alone
      tags:
       - latest
       - ${DRONE_BUILD_NUMBER}

  - name: start_lico_alone
    image: appleboy/drone-ssh
    settings:
      host:
        - ligo.ml
      port: 22
      username:
        from_secret: ssh_user_name
      password:
        from_secret: ssh_password
    script:
      - docker stop local_lico_alone
      - docker rm local_lico_alone
      - docker rmi lico603/lico_alone
      - docker run -p 81:80 lico603/lico_alone

volumes:
  - name: cache
    host:
      path: /tmp/cache
