kind: pipeline
name: default

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - /drone/src/gopath
        - /drone/src/docker_cache

  - name: build_binary
    image: golang
    privileged: true
    commands:
      - export GOPATH=/drone/src/gopath
      - export CGO_ENABLED=0
      - echo $GOPATH
      - go build
      - go test
      - mv lico_alone ./docker/lico_alone

  - name: build_docker_image
    image: plugins/docker
    settings:
      storage_path: /drone/src/docker_cache
      use_cache: true
      username:
        from_secret: docker_hub_user_name
      password:
        from_secret: docker_hub_password
      dockerfile: ./docker/Dockerfile
      context: ./docker/
      repo: lico603/lico_alone
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /drone/src/gopath
        - /drone/src/docker_cache

  - name: start_lico_alone
    image: appleboy/drone-ssh
    settings:
      host:
        - ligo.ml
      port: 22
      username:
        from_secret: ssh_user_name
      password:
        from_secret: ssh_password
      script:
        - echo "begin ssh"
        - docker stop local_lico_alone
        - docker rm local_lico_alone
        - docker rmi -f lico603/lico_alone
        - docker run -d -p 81:80 lico603/lico_alone

volumes:
  - name: cache
    host:
      path: /tmp/cache
