kind: pipeline
name: default

steps:
  - restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /root/go
    volumes:
      - /var/local/drone-cache:/cache
  - name: build_binary
    image: golang
    privileged: true
    commands:
      - go test
      - go build
      - mv lico_alone ./docker/
      - ls -al
  - name: build_docker_image
    image: plugins/docker

    settings:
      username:
        from_secret: docker_hub_user_name
      password:
        from_secret: docker_hub_password
      dockerfile: ./docker/Dockerfile
      context: ./docker/
      repo: lico603/lico_alone
      tags:
       - latest
       - ${DRONE_BUILD_NUMBER}
  - name: start_lico_alone
    image: appleboy/drone-ssh
    host: ligo.ml
    port: 22
    username:
      from_secret: ssh_user_name
    password:
      from_secret: ssh_password

    script:
      - docker stop local_lico_alone
      - docker rm local_lico_alone
      - docker rmi lico603/lico_alone
      - docker run lico603/lico_alone
  - rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /root/go
    volumes:
      - /var/local/drone-cache:/cache






