kind: pipeline
name: default

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - /drone/src/gopath
        - /drone/src/docker_cache

  - name: build_binary
    image: golang
    privileged: true
    commands:
      - export GOPATH=/drone/src/gopath
      - go build
      - go test
      - mv lico_alone ./docker/

  - name: build_docker_image
    image: plugins/docker
    environment:
      - DOCKER_OPTS:"-g /drone/src/docker_cache"
    settings:
      username:
        from_secret: docker_hub_user_name
      password:
        from_secret: docker_hub_password
      dockerfile: ./docker/Dockerfile
      context: ./docker/
      repo: lico603/lico_alone
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /drone/src/gopath
        - /drone/src/docker_cache

  - name: start_lico_alone
    image: appleboy/drone-ssh
    settings:
      host:
        - ligo.ml
      port: 22
      username:
        from_secret: ssh_user_name
      password:
        from_secret: ssh_password
    script:
      - docker stop local_lico_alone
      - docker rm local_lico_alone
      - docker rmi lico603/lico_alone
      - docker run -p 81:80 lico603/lico_alone

volumes:
  - name: cache
    host:
      path: /tmp/cache
