[ali_sms]
key = "123"
secret = "123"

[db]
conn_max_left_time = 14400
conn_str = "root:123456@tcp(localhost:3306)/myapp?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
max_idle_conn = 10
max_open_conn = 5
migration_path = "/migrations"

[email]
address = "livo@example.top"
host = "smtpdm.example.com"
password = "123"
port = 465
user_name = "livo@example.top"

[file_save]
channel = "qiniu"
oss_bucket = "common"
oss_end_point = "http://oss.example.top"
oss_key = "123"
oss_secret = "123"

[http]
enable_swagger = true
gin_mode = "debug"
port = 80
ssl_pri = ""
ssl_pub = ""
url = "https://example.top"

[jwt]
hs_256_key = "123"
normal_exp_duration = 604800

[log]
log_file = "stdout"
log_level = 5
