service:
  port: 81
db:
  ip: 192.168.31.238
  port: 3306
  user: root
  password: 123456
  database: user
  max_open_conn: 1
  max_idle_conn: 1
  conn_max_left_time:  3600*7 #in second

jwt: #用于生成jwt
  public_key: ""
  private_key: ""
  hs256_key: "E5Vsfs#$afasdrtfawe*^&%("
  #app_exp_duration: 23 #app角色用戶的過期時間 app再算
  normal_exp_duration: 345 #其他用戶的過期時間

ssl:
  public_key: ""
  private_key: ""
