http_port: 80
gin_mode: debug
ssl_pri: ""
ssl_pub: ""
enable_swagger: true

db:
  conn_max_left_time: 25200
  db_name: lico
  host: rpi.lizo.top
  max_idle_conn: 1
  max_open_conn: 1
  password: "123456"
  port: 3306
  user: root
file_save:
  local_file_save_dir: static_files
  local_file_save_url: http://localhost/static_files
  oss_bucket: local
  oss_end_point: local
  oss_key: local
  oss_secret: local
  save_type: local
jwt:
  hs256_key: E5Vsfs#$afasdrtfawe*^&%(
  normal_exp_duration: 2592000
  private_key_path: E5Vsfs#$afasdrtfawe*^&%(
