basePath: '{{.BasePath}}'
definitions:
  com_model.CommonReturn:
    properties:
      code:
        example: 400
        type: integer
      data:
        description: 数据值
        type: object
      detail:
        description: 可由运行模式控制是否显示
        example: 错误的详细信息，用于排查错误
        type: string
      message:
        example: 错误信息
        type: string
    type: object
  model.IcpInfo:
    properties:
      label:
        type: string
      link:
        type: string
      name:
        type: string
    type: object
  model.UpdateArticleModel:
    properties:
      content:
        type: string
      description:
        type: string
      id:
        type: string
      picture:
        type: string
      sort:
        type: integer
      title:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: This is a sample server Petstore server.
  license: {}
  title: Swagger Example API
  version: 0.0.1
paths:
  /api/common/article/get_article:
    get:
      description: 获取article
      operationId: 获取article
      parameters:
      - description: 搜索内容
        in: query
        name: article_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 获取article
      tags:
      - 公共接口
  /api/common/article/query_sample:
    get:
      description: 查询文章列表
      operationId: 查询文章列表
      parameters:
      - description: 搜索内容
        in: query
        name: search_key
        required: true
        type: string
      - description: 页索引
        in: query
        name: page_num
        required: true
        type: integer
      - description: 页大小
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 查询文章列表
      tags:
      - 公共接口
  /api/common/icp_info:
    get:
      description: Icp信息
      operationId: Icp信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.IcpInfo'
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Icp信息
      tags:
      - 公共接口
  /api/manage/article/delete:
    post:
      description: 删除文章
      operationId: 删除文章
      parameters:
      - description: 文章id
        in: query
        name: article_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 删除文章
      tags:
      - 文章管理
  /api/manage/article/get_by_id:
    get:
      description: 获取一个文章信息
      operationId: 获取一个文章信息
      parameters:
      - description: 文章id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 通过id获取文章
      tags:
      - 文章管理
  /api/manage/article/query:
    get:
      description: 查询文章列表
      operationId: 查询文章列表
      parameters:
      - description: 搜索内容
        in: query
        name: search_key
        required: true
        type: string
      - description: 页索引
        in: query
        name: page_num
        required: true
        type: integer
      - description: 页大小
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 查询文章列表
      tags:
      - 文章管理
  /api/manage/article/update:
    post:
      description: 更新文章内容
      operationId: 更新文章内容
      parameters:
      - description: 文章内容
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.UpdateArticleModel'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 更新文章内容
      tags:
      - 文章管理
  /api/manage/file/delete:
    post:
      description: 文件删除
      operationId: 文件删除
      parameters:
      - description: 文件记录id
        in: formData
        name: file_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 文件删除
      tags:
      - 文件管理
  /api/manage/file/query:
    post:
      description: 文件查询
      operationId: 文件查询
      parameters:
      - description: page_num页索引
        in: query
        name: page_num
        required: true
        type: integer
      - description: page_size页大小
        in: query
        name: page_size
        required: true
        type: integer
      - description: key_name_like
        in: formData
        name: key_name_like
        required: true
        type: string
      - description: bucket_name_like
        in: formData
        name: bucket_name_like
        required: true
        type: string
      - description: url_like
        in: formData
        name: url_like
        required: true
        type: string
      - description: user_id
        in: formData
        name: user_id
        required: true
        type: string
      - description: biz_type
        in: formData
        name: biz_type
        required: true
        type: string
      - description: content_type
        in: formData
        name: content_type
        required: true
        type: string
      - description: created_at_begin
        in: formData
        name: created_at_begin
        required: true
        type: string
      - description: created_at_end
        in: formData
        name: created_at_end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 文件查询
      tags:
      - 文件管理
  /api/manage/file/upload:
    post:
      description: 文件上传
      operationId: 文件上传
      parameters:
      - description: 单个文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 文件上传
      tags:
      - 文件管理
  /api/manage/setting/get_setting_all:
    post:
      description: 获取所有配置项
      operationId: 获取所有配置项
      parameters:
      - description: 搜索值
        in: query
        name: searchKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 获取所有配置项
      tags:
      - 配置项
  /api/manage/setting/update_config:
    post:
      description: 更新配置项
      operationId: 更新配置项
      parameters:
      - description: 配置名
        in: formData
        name: name
        required: true
        type: string
      - description: 配置值
        in: formData
        name: value
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 更新配置项
      tags:
      - 配置项
  /api/user/login:
    post:
      description: 用户用密码登录
      operationId: 用户登录
      parameters:
      - description: 用户手机号
        in: formData
        name: phone
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 2000 {token:"asb"}
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户
  /api/user/register:
    post:
      description: 用户注册
      operationId: 用户注册
      parameters:
      - description: 用户手机号
        in: formData
        name: phone
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        required: true
        type: string
      - description: 验证码
        in: formData
        name: valid_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 用户注册
      tags:
      - 用户
  /api/user/send_sms:
    post:
      description: 用户发短信
      operationId: 用户发短信
      parameters:
      - description: 用户手机号
        in: formData
        name: phone
        required: true
        type: string
      - description: register login change_password
        in: formData
        name: send_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/com_model.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 用户发短信
      tags:
      - 用户
  /health:
    get:
      description: 健康检查Hello 返回hello字样
      operationId: 健康检查Hello
      responses:
        "200":
          description: hello
          schema:
            type: string
      summary: 健康检查Hello
      tags:
      - 健康检查
  /health/ping:
    get:
      description: 健康检查Ping 检查数据库是否正常 并返回启动时间
      operationId: 健康检查Ping
      responses:
        "200":
          description: pong start time up time
          schema:
            type: string
      summary: 健康检查Ping
      tags:
      - 健康检查
  /version:
    get:
      description: Version
      operationId: Version
      responses:
        "200":
          description: version build_time git_commit go_version
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Version
      tags:
      - 公共接口
swagger: "2.0"
