GET https://httpbin.org/ip
Accept: application/json

###
GET https://httpbin.org/get?show_env=1
Accept: application/json

###
### Get request with environment variables
#GET {{host}}/get?show_env={{show_env}}
#Accept: service/json

### Get request with disabled redirects
# @no-redirect
GET http://httpbin.org/status/301

### POST 请求
### Send POST request with json body
POST https://httpbin.org/post
Content-Type: application/json

{
  "id": 999,
  "value": "content",
  "ok": "success"
}

### Send POST request with body as parameters
POST https://httpbin.org/post
Content-Type: application/x-www-form-urlencoded

id=999&value=content&test=工

### Send a form with the text and file fields
POST https://httpbin.org/post
Content-Type: multipart/form-data; boundary=WebAppBoundary

###
