// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package nlog

import (
	"github.com/google/wire"
	"github.com/krilie/lico_alone/common/model/context-enum"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func InitNLog(runEnv context_enum.RunEnv, level logrus.Level) *NLog {
	nLog := NewLogger(runEnv, level)
	return nLog
}

// wire.go:

var NLogProviderSet = wire.NewSet(NewLogger)
