// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package nlog

import (
	"github.com/google/wire"
	"github.com/krilie/lico_alone/common/config"
	"github.com/krilie/lico_alone/common/const-val"
)

// Injectors from wire.go:

func InitNLog() *NLog {
	runEnv := _wireRunEnvValue
	config := _wireConfigValue
	nLog := NewLogger(runEnv, config)
	return nLog
}

var (
	_wireRunEnvValue = const_val.RunEnv
	_wireConfigValue = config.Cfg
)

// wire.go:

var NLogProviderSet = wire.NewSet(NewLogger)
