basePath: '{{.BasePath}}'
definitions:
  cmodel.CommonReturn:
    properties:
      code:
        example: 400
        type: integer
      data:
        description: 数据值
        type: object
      detail:
        description: 可由运行模式控制是否显示
        example: 错误的详细信息，用于排查错误
        type: string
      message:
        example: 错误信息
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: This is a sample server Petstore server.
  license: {}
  title: Swagger Example API
  version: 0.0.1
paths:
  /api/user/login:
    post:
      description: 用户用密码登录
      operationId: 用户登录
      parameters:
      - description: 用户手机号
        in: formData
        name: phone
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{jwt:"asb"}'
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
      summary: 用户登录
      tags:
      - 用户账号
  /api/user/register:
    post:
      description: 用户注册
      operationId: 用户注册
      parameters:
      - description: 用户手机号
        in: formData
        name: phone
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        required: true
        type: string
      - description: 验证码
        in: formData
        name: valid_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
      summary: 用户注册
      tags:
      - 用户账号
  /api/user/send_sms:
    post:
      description: 用户发短信
      operationId: 用户发短信
      parameters:
      - description: 用户手机号
        in: formData
        name: phone
        required: true
        type: string
      - description: register login change_password
        in: formData
        name: send_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/cmodel.CommonReturn'
            type: object
      summary: 用户发短信
      tags:
      - 用户发短信
swagger: "2.0"
