name: Go
on:
  push:
    branches:
      - catchword
jobs:

  build:
    name: 构建部署
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v1
      - name: 设置golang1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: 使用golang包缓存
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # 自动化测试时使用的配置信息
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: # optional, default is 3306
          character set server: # optional, default is utf8mb4
          collation server: # optional, default is utf8mb4_general_ci
          mysql version: # optional, default is latest
          mysql root password: # optional, default is
          mysql database: # optional, default is
          mysql user: # optional, default is
          mysql password: # optional, default is
      - name: golang测试与golang构建
        env:
          CGO_ENABLED: 0
        run: |
          cd server
          export MYAPP_TEST_CONFIG='${{ secrets.TEST_CONFIG }}'
          export TZ='Asia/Shanghai'
          go build -ldflags "-X 'github.com/krilie/lico_alone/common/run_env.VERSION=`cat ../version`' -X 'github.com/krilie/lico_alone/common/run_env.BUILD_TIME=`date "+%Y-%m-%d %H:%M:%S"`' -X 'github.com/krilie/lico_alone/common/run_env.GO_VERSION=`go version`' -X 'github.com/krilie/lico_alone/common/run_env.GIT_COMMIT=${GITHUB_SHA}'"  -v .
          go test -run Auto -v ./...
          cd ..

      - name: 复制文件到docker文件夹&&设置环境变量
        run: |
          cp ./server/lico_alone ./docker/lico_alone
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAGS_LATEST=latest" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAGS_VERSION=$(cat version)" >> $GITHUB_ENV
          echo "TZ=Asia/Shanghai" >> $GITHUB_ENV

      - name: 构建与推送镜像
        uses: docker/build-push-action@v1.1.0
        env:
          TAG: ${{ github.sha }}
          TZ: "Asia/Shanghai"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          path: ./docker
          repository: ${{ secrets.DOCKER_IMAGE_NAME }}
          tags: ${{ env.DOCKER_IMAGE_TAGS_VERSION }},${{ env.GITHUB_SHA_SHORT }}

      - name: 部署
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker service update --no-resolve-image --with-registry-auth --image ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }} myapp_myapp
