name: Go
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          TZ=Asia/Shanghai
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
          go build -ldflags "-X 'main.VERSION=`cat version`' -X 'main.BUILD_TIME=`date "+%Y-%m-%d %H:%M:%S"`' -X 'main.GO_VERSION=`go version`' -X 'main.GIT_COMMIT=${GITHUB_SHA}'"  -v .

      - name: copy-file-to-docker
        run: |
          cp ./lico_alone ./docker/lico_alone
          cp -rf ./www ./docker/www
          export DOCKER_IMAGE_TAGS="latest,"`cat version`

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          MY_FIRST: 1111
          MY_SECOND: 2222
        with:
          name: ${{ secrets.DOCKER_IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          workdir: ./docker
          tags: DOCKER_IMAGE_TAGS
          snapshot: true

      - name: apply app server
        uses: appleboy/ssh-action@master
        env:
          IMAGE: ${{ secrets.DOCKER_IMAGE_NAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
              ls -h