name: Go
on:
  push:
    branches:
      - develop
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v .

      - name: copy-file-to-docker
        run: cp ./lico_alone ./docker/lico_alone

      - name: build-push-docker-image
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
          TAG_NAME: "v0.0.1"
#          LATEST: "true"