name: Go
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          go build -ldflags "-X 'main.VERSION=`cat version`' -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`' -X 'main.GIT_COMMIT=${GITHUB_SHA}'"  -v .
          pwd
          ls -h

      - name: copy-file-to-docker
        run: |
          cp ./lico_alone ./docker/lico_alone
          cp -rf ./www ./docker/www

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          workdir: ./docker
          tags: ${{ "latest,"`cat version` }}

      - name: apply app server
        uses: appleboy/ssh-action@master
        env:
          IMAGE: ${{ secrets.DOCKER_IMAGE_NAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/app-server
            pwd
            docker-compose down
            echo ${IMAGE}
            docker rmi registry.cn-qingdao.aliyuncs.com/lizo/app-server:latest
            docker-compose up -d